name: Build

on:
   push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
   pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'

   workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
          
        name: Install dependencies
      - run: npm install
